Repository dwdab/ws20-devops-calc, pull requests merged in 2021-02, with the labels that each got.

#13 chore(index.js) #11 code maintenance delete function toNumber
  index.js
  ws20-devops-calc.iml
Labels: enhancement

#16 feat(index.js) #15 Include the function multiplication(x,y)
  index.js
Labels: enhancement

#14 fix(index.js) #12 bug no calculation of decimal numbers
  index.js
Labels: bug

#18 Readme include usage
  README.md
  index.js
Labels: documentation

#17 Added Modulo operation
  README.md
  index.js
Labels: enhancement

#25 feat implement a generalized subtraction
  index.js
  operations/subtraction.js
Labels: enhancement

#27 Generalized division
  index.js
  operations/division.js
Labels: enhancement

#26 Generalized Multiplication
  index.js
  operations/multiplication.js
Labels: enhancement

#30 modularized power with npm
  index.js
  operations/power.js
  package-lock.json
  package.json
Labels: enhancement
